name: Dancing with Tigers
favicon: null
layout_spectrum: 0.2849462
typography_spectrum: 0.344086
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#D4943B'
    - '#BC5431'
    - '#AEAEAE'
    - '#FBF180'
  brandStrength: 0.5
  lightness: 0.7581369
  saturation: 0.5
  rhythmicContrast: 0.4749104
purpose: []
