typography_spectrum: 0.344086
color:
  brandColors:
    - '#FFFFFF'
    - '#D4943B'
    - '#BC5431'
    - '#AEAEAE'
    - '#FBF180'
  brandStrength: 0.5
  lightness: 0.7581369
  saturation: 0.5
  rhythmicContrast: 0.4749104
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49229
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Aditya
  email: adityaj@adipa.com
  url: www.dancingwithtigers.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe82714e-6f85-4166-aa1d-2544152379de.png
name: Dancing with Tigers
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d01d8462-9c13-43c7-9fb9-0fdb4440fbb2.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: BElieve in YOUrself!
purpose: []
