name: Dancing with Tigers
favicon: null
layout_spectrum: 0.16611185087822378
typography_spectrum: 0.1093502591829747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5267198451329023
  lightness: 0.7581369320396334
  saturation: 0.28170979698188603
  rhythmicContrast: 0.3995582894422114
purpose: []
