favicon: null
name: Dancing with Tigers
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2817098
  brandStrength: 0.5267198451329023
  lightness: 0.7581369
  brandColors:
    - '#FFFFFF'
    - '#D4943B'
    - '#BC5431'
    - '#AEAEAE'
    - '#FBF180'
  rhythmicContrast: 0.4749104
typography_spectrum: 0.344086
layout_spectrum: 0.2849462
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
